name: Docker Image CI

on:
  push:
    branches: [ "first_version" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Determine Docker Tag
      run: |
        export REPO=orlevi/newsletter-agent
        if [[ "${{ github.event_name }}" == "push" && "${{ github.ref_type }}" == "tag" ]]; then
          echo "DOCKER_TAGS=${REPO}:${{ github.ref_name }},${REPO}:latest" >> $GITHUB_ENV
        else
          echo "DOCKER_TAGS=${REPO}:nightly" >> $GITHUB_ENV
        fi

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ env.DOCKER_TAGS }}
        cache-from: type=registry,ref=orlevi/newsletter-agent:cache
        cache-to: type=registry,ref=orlevi/newsletter-agent:cache,mode=max

    - name: GH Release
      if: github.ref_type == 'tag'
      uses: docker://antonyurchenko/git-release:v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
