name: Docker Image CI

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Determine Docker Tag
      run: |
        export REPO="orlevi/newsletter-agent"
        echo "ref_type=${{ github.ref_type }}"
        DOCKER_TAGS=${REPO}:${{ github.ref_name }},${REPO}:latest
        echo "DOCKER_TAGS=${DOCKER_TAGS}" >> $GITHUB_ENV
        echo "Tags: $DOCKER_TAGS"

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ env.DOCKER_TAGS }}
        cache-from: type=registry,ref=orlevi/newsletter-agent:cache
        cache-to: type=registry,ref=orlevi/newsletter-agent:cache,mode=max

    - name: GH Release
      uses: docker://antonyurchenko/git-release:v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
